export default [
  {
    user: "Roberto Andrés",
    product: 1,
    productName: "Baberos",
    quantity: 3,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda.1234 #321",
  },
  {
    user: "Edificio Adefesio",
    product: 1,
    productName: "Baberos",
    quantity: 6,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda. Amunategui #573 depto 1801",
  },
  {
    user: "Kansas City",
    product: 1,
    productName: "Baberos",
    quantity: 6,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda. San pablo #2170 depto 303",
  },
  {
    user: "Super Mega Killer",
    product: 2,
    productName: "Mitones",
    quantity: 2,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda.1234 #321",
  },
  {
    user: "Yasna Rozas",
    product: 3,
    productName: "Gorros",
    quantity: 1,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda.1234 #321",
  },
  {
    user: "Loanne Martina",
    product: 9,
    productName: "Pañal Algodon",
    quantity: 3,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda.1234 #321",
  },
  {
    user: "Felipe Ignacio",
    product: 4,
    productName: "Bodies",
    quantity: 9,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda.1234 #321",
  },
  {
    user: "Monica Nelly",
    product: 7,
    productName: "Poleras",
    quantity: 8,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda.1234 #321",
  },
  {
    user: "Carlos Germán",
    product: 5,
    productName: "Pantalones",
    quantity: 7,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda.1234 #321",
  },
  {
    user: "Anastasio Mercedesio",
    product: 10,
    productName: "Pañal RN",
    quantity: 2,
    region: "Metropolitana de Santiago",
    comuna: "Santiago",
    address: "Avda.1234 #321",
  },
];
