const ProductMock = [
  { id: 1, typeId: 1, name: "Baberos" },
  { id: 2, typeId: 1, name: "Mitones" },
  { id: 3, typeId: 1, name: "Gorros" },
  { id: 4, typeId: 1, name: "Bodies" },
  { id: 5, typeId: 1, name: "Patalones" },
  { id: 6, typeId: 1, name: "Calcetines" },
  { id: 7, typeId: 1, name: "Poleras" },
  { id: 8, typeId: 1, name: "Camisetas" },
  { id: 9, typeId: 1, name: "Pañal Algodón" },
  { id: 10, typeId: 2, name: "Pañal RN" },
  { id: 11, typeId: 2, name: "Pañal RN+" },
  { id: 12, typeId: 2, name: "Pañal P" },
  { id: 13, typeId: 2, name: "Pañal M" },
  { id: 14, typeId: 3, name: "Sábanas" },
  { id: 15, typeId: 3, name: "Cojines Recién Nacido" },
  { id: 16, typeId: 3, name: "Toallas De Baño" },
  { id: 17, typeId: 3, name: "Mantas" },
  { id: 18, typeId: 3, name: "Cubre Colchón" },
  { id: 19, typeId: 4, name: "Chupete" },
  { id: 20, typeId: 4, name: "Mamadera" },
  { id: 21, typeId: 4, name: "Juguetes (Móviles/Sonajeros/Otros)" },
  { id: 22, typeId: 4, name: "Vitaminas" },
  { id: 23, typeId: 4, name: "Termómetro" },
  { id: 24, typeId: 4, name: "Escobillas Aseo Mamaderas" },
  { id: 25, typeId: 4, name: "TijerasPuntas Redondeadas" },
  { id: 26, typeId: 4, name: "Cojín De Lactancia" },
  { id: 27, typeId: 4, name: "Libros De Estimulación Temprana" },
  { id: 28, typeId: 5, name: "Cuna" },
  { id: 29, typeId: 5, name: "Bañera" },
  { id: 30, typeId: 5, name: "Silla de comer" },
  { id: 31, typeId: 5, name: "Corral" },
  { id: 32, typeId: 5, name: "Mudador" },
  { id: 33, typeId: 5, name: "Organizador" },
  { id: 34, typeId: 5, name: "Moíses" },
  { id: 35, typeId: 5, name: "Nido Colecho" },
  { id: 36, typeId: 6, name: "Toallas Húmedas" },
  { id: 37, typeId: 6, name: "Jabón Neutro" },
  { id: 38, typeId: 6, name: "Shampoo Neutro" },
  { id: 39, typeId: 6, name: "Cepillo/Peine De Seda" },
  { id: 40, typeId: 6, name: "Pómada Coceduras" },
  { id: 41, typeId: 6, name: "Colonia" },
  { id: 42, typeId: 6, name: "Emulsionado" },
  { id: 43, typeId: 7, name: "Leche" },
];
export default ProductMock;
